# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
target 'kanaHenkan' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Alamofire' 
  pod 'PKHUD', '~> 5.0'
  pod 'IQKeyboardManagerSwift'

  # Pods for kanaHenkan

  target 'kanaHenkanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kanaHenkanUITests' do
    # Pods for testing
  end

end
